### ISSUE TITLE
Promises hang on empty selection result

### ISSUE THREAD

**Issue by jmzhang** [julianshapiro/velocity#665]
`var promise = $.Velocity.animate($('.something-not-exist'), { duration: 100 });`

I'm expecting the returned `promise` to be completed with either a success or a rejection, but it ends up being pending forever. 

Personally, I prefer the promise to be resolved immediately in this case.

**Comment by john-goldsmith** [comment]
I just ran into this as well when unknowingly passing Velocity an empty `NodeList`.

```js
// Returns a "pending" Promise that will never resolve or reject
Velocity(document.querySelectorAll('.something-not-exist'), {duration: 100});

// This is ok -- Velocity returns undefined, so chaining `then` will throw
Velocity(document.querySelector('#something-not-exist'), {duration: 100});
```

**Comment by Rycochet** [comment]
Promises should always resolve one way or another - my personal view is that this should succeed as we don't know if being passed an empty NodeList is deliberate or not - possibly add an option to `rejectOnEmpty` or similar though?

**Comment by Rycochet** [comment]
Should be fixed now, documentation needs to add the option for rejecting instead of resolving nuder the "Feature: Promises" section @kvirani 

---

If no elements (or an empty list) are passed then the promise is *rejected*, however passing ```promiseRejectEmpty:false``` to the options will allow for it to resolve instead which can be useful if wanting the same completion path on an unknown, and possibly empty, list of elements.

**Comment by laurenbenichou** [comment]
Hey there, 

Seems like this should work then?

```
var animSeq = [
				{
					e: $hovElParent,
					p: {
						opacity: 0
					},
					o: {
						duration: 150,
						easing: cubicBezier
					}
				},
				{
					e: $header,
					p: {
						translateY: -60
					},
					o: {
						duration: 500,
						easing: cubicBezier
					}
				},
				{
					e: $prevSlices,
					p: {
						translateY: -600
					},
					o: {
						duration: 500,
						sequenceQueue: false,
						easing: cubicBezier,
						promiseRejectEmpty: false
					}
				},
				{
					e: $nextSlices,
					p: {
						translateY: 600
					},
					o: {
						duration: 500,
						sequenceQueue: false,
						easing: cubicBezier,
						promiseRejectEmpty: false,
						complete: function() {
							window.location.href = $hovElParent.data().link;
						}
					}
				}
			];
```

$prevSlice is sometimes empty but the sequence still doesn't get completed. Am I using this the wrong way?

**Comment by laurenbenichou** [comment]
Unless this doesn't work with Velocity UI pack.

**Comment by Rycochet** [comment]
@laurenbenichou Please don't paste long sections of code - put them in a JSFiddle and link to it instead so we can actually see what you mean - especially when it's a partial bit of code that cannot run on it's own.

If I remember correctly there are issues with Promises and the ui-pack - it's not something I've had a chance to look into yet (searching shows several open issues relating to Promises).

**Comment by laurenbenichou** [comment]
@Rycochet Sure, no problem. I copy-pasted last minute before leaving work. It's basically the same code you have in your documentation. 

```
var mySequence = [
    { e: $element1, p: { translateX: 100 }, o: { duration: 1000 } },
    { e: $element2, p: { translateX: 200 }, o: { duration: 1000 } },
    { e: $element3, p: { translateX: 300 }, o: { duration: 1000 } }
];
```

And I am 100% sure that it stops after $element2 because it return an empty NodeList. When I have more time today, I will put  together a JSFiddle together. 

Thank you for your quick response.
